/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundry.form;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import laundry.model.Pelanggan;

/**
 *
 * @author fahmi
 */
public class PelangganForm extends javax.swing.JFrame {

//    KODING KU
    Pelanggan pelanggan = new Pelanggan();
    
    public void tampilData(){
        ArrayList<Pelanggan> list = pelanggan.read();
        
        DefaultTableModel tableModel = (DefaultTableModel) tbPelanggan.getModel();
        tableModel.setRowCount(0);
        
        Object[] row = new Object[4];
        
        if(list.size() > 0){
//            System.out.println("Jalan");
            for (int i = 0; i<list.size(); i++){
                row[0] = list.get(i).getId_pel();
                row[1] = list.get(i).getNama();
                row[2] = list.get(i).getAlamat();
                row[3] = list.get(i).getPhone();
                
                
//                KODE OTOMATIS
                String kodeAsli = list.get(i).getId_pel();
                int kodeAngka =(Integer.parseInt(kodeAsli.substring(1))+1);
//                System.out.println(kodeAngka);
                
                id_pelangganTF.setText(String.valueOf("P"+kodeAngka));
                tableModel.addRow(row);
            }
        }else if(list.size() == 0){
            id_pelangganTF.setText("P1");
        }
    }
    
    public void tampilCari(){
        ArrayList<Pelanggan> list = pelanggan.search(cariTF.getText());
        
        DefaultTableModel tableModel = (DefaultTableModel) tbPelanggan.getModel();
        tableModel.setRowCount(0);
        
        Object[] row = new Object[4];
        
        if(list.size() > 0){
//            System.out.println("Jalan");
            for (int i = 0; i<list.size(); i++){
                row[0] = list.get(i).getId_pel();
                row[1] = list.get(i).getNama();
                row[2] = list.get(i).getAlamat();
                row[3] = list.get(i).getPhone();
                
                tableModel.addRow(row);
            }
        }
    }
    
    public void reset() {
        id_pelangganTF.setEnabled(false);
        pelangganTF.setText("");
        alamatTA.setText("");
        telpTF.setText("");
        BTtambah.setEnabled(true);
        BTubah.setEnabled(false);
        BThapus.setEnabled(false);
        tampilData();
      }

    /**
     * Creates new form PelangganForm
     */
    public PelangganForm() {
        initComponents();
        reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbPelanggan = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        id_pelangganTF = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        BTtambah = new javax.swing.JButton();
        BTbersih = new javax.swing.JButton();
        BThapus = new javax.swing.JButton();
        BTkeluar = new javax.swing.JButton();
        BTubah = new javax.swing.JButton();
        cariTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pelangganTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamatTA = new javax.swing.JTextArea();
        telpTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Pelanggan", "Nama", "Alamat", "Telpon"
            }
        ));
        tbPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPelanggan);

        jLabel3.setText("Id");

        BTtambah.setText("Tambah");
        BTtambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTtambahActionPerformed(evt);
            }
        });

        BTbersih.setText("Bersih");
        BTbersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTbersihActionPerformed(evt);
            }
        });

        BThapus.setText("Hapus");
        BThapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BThapusActionPerformed(evt);
            }
        });

        BTkeluar.setText("Keluar");
        BTkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTkeluarActionPerformed(evt);
            }
        });

        BTubah.setText("Ubah");
        BTubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTubahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(BTtambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTubah)
                .addGap(18, 18, 18)
                .addComponent(BTbersih)
                .addGap(18, 18, 18)
                .addComponent(BThapus)
                .addGap(18, 18, 18)
                .addComponent(BTkeluar)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTtambah)
                    .addComponent(BTbersih)
                    .addComponent(BThapus)
                    .addComponent(BTkeluar)
                    .addComponent(BTubah))
                .addContainerGap())
        );

        cariTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cariTFKeyTyped(evt);
            }
        });

        jLabel1.setText("Nama");

        jLabel7.setText("Cari Berdasarkan Nama / Alamat");

        jLabel2.setText("Alamat");

        alamatTA.setColumns(20);
        alamatTA.setRows(5);
        jScrollPane2.setViewportView(alamatTA);

        jLabel4.setText("Telpon");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pelangganTF, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(id_pelangganTF, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telpTF, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cariTF, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_pelangganTF, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pelangganTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(telpTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cariTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        setSize(new java.awt.Dimension(525, 552));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPelangganMouseClicked
        id_pelangganTF.setText(tbPelanggan.getValueAt(tbPelanggan.getSelectedRow(), 0).toString());
        pelangganTF.setText(tbPelanggan.getValueAt(tbPelanggan.getSelectedRow(), 1).toString());
        alamatTA.setText(tbPelanggan.getValueAt(tbPelanggan.getSelectedRow(), 2).toString());
        telpTF.setText(tbPelanggan.getValueAt(tbPelanggan.getSelectedRow(), 3).toString());
        BTtambah.setEnabled(false);
        BTubah.setEnabled(true);
        BThapus.setEnabled(true);
    }//GEN-LAST:event_tbPelangganMouseClicked

    private void BTbersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTbersihActionPerformed
        reset();
    }//GEN-LAST:event_BTbersihActionPerformed

    private void BTkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTkeluarActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this,
            "Konfirmasi Keluar Aplikasi",
            "Yakin untuk keluar dari program",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_BTkeluarActionPerformed

    private void BTtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTtambahActionPerformed
        pelanggan.setId_pel(id_pelangganTF.getText());
        pelanggan.setNama(pelangganTF.getText());
        pelanggan.setAlamat(alamatTA.getText());
        pelanggan.setPhone(telpTF.getText());

        if (pelanggan.create()){
            tampilData();
            JOptionPane.showMessageDialog(null, "Berhasil Di Simpan");
            reset();
        }else{
            JOptionPane.showMessageDialog(null, "Gagal Di Simpan");
        }
    }//GEN-LAST:event_BTtambahActionPerformed

    private void BTubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTubahActionPerformed
        pelanggan.setId_pel(id_pelangganTF.getText());
        pelanggan.setNama(pelangganTF.getText());
        pelanggan.setAlamat(alamatTA.getText());
        pelanggan.setPhone(telpTF.getText());

        if (pelanggan.update()){
            tampilData();
            JOptionPane.showMessageDialog(null, "Berhasil Di Ubah");
            reset();
        }else{
            JOptionPane.showMessageDialog(null, "Gagal Di Ubah");
        }
    }//GEN-LAST:event_BTubahActionPerformed

    private void BThapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BThapusActionPerformed
        try {
            int jawab;

            if ((jawab = JOptionPane.showConfirmDialog(null, "Ingin menghapus data?", "konfirmasi", JOptionPane.YES_NO_OPTION)) == 0) {
                pelanggan.setId_pel(id_pelangganTF.getText());

                if (pelanggan.delete()){
                    tampilData();
                    JOptionPane.showMessageDialog(null, "Berhasil Di Hapus");
                    reset();
                }else{
                    JOptionPane.showMessageDialog(null, "Gagal Di Hapus");
                }

                tampilData();
                reset();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_BThapusActionPerformed

    private void cariTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariTFKeyTyped
        tampilCari();
    }//GEN-LAST:event_cariTFKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PelangganForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PelangganForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PelangganForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PelangganForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PelangganForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTbersih;
    private javax.swing.JButton BThapus;
    private javax.swing.JButton BTkeluar;
    private javax.swing.JButton BTtambah;
    private javax.swing.JButton BTubah;
    private javax.swing.JTextArea alamatTA;
    private javax.swing.JTextField cariTF;
    private javax.swing.JTextField id_pelangganTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField pelangganTF;
    private javax.swing.JTable tbPelanggan;
    private javax.swing.JTextField telpTF;
    // End of variables declaration//GEN-END:variables
}
